require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/confederations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Confederation. As you add validations to Confederation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Confederation.create! valid_attributes
      get confederations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      confederation = Confederation.create! valid_attributes
      get confederation_url(confederation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_confederation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      confederation = Confederation.create! valid_attributes
      get edit_confederation_url(confederation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Confederation" do
        expect {
          post confederations_url, params: { confederation: valid_attributes }
        }.to change(Confederation, :count).by(1)
      end

      it "redirects to the created confederation" do
        post confederations_url, params: { confederation: valid_attributes }
        expect(response).to redirect_to(confederation_url(Confederation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Confederation" do
        expect {
          post confederations_url, params: { confederation: invalid_attributes }
        }.to change(Confederation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post confederations_url, params: { confederation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested confederation" do
        confederation = Confederation.create! valid_attributes
        patch confederation_url(confederation), params: { confederation: new_attributes }
        confederation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the confederation" do
        confederation = Confederation.create! valid_attributes
        patch confederation_url(confederation), params: { confederation: new_attributes }
        confederation.reload
        expect(response).to redirect_to(confederation_url(confederation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        confederation = Confederation.create! valid_attributes
        patch confederation_url(confederation), params: { confederation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested confederation" do
      confederation = Confederation.create! valid_attributes
      expect {
        delete confederation_url(confederation)
      }.to change(Confederation, :count).by(-1)
    end

    it "redirects to the confederations list" do
      confederation = Confederation.create! valid_attributes
      delete confederation_url(confederation)
      expect(response).to redirect_to(confederations_url)
    end
  end
end
