require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/football_organizations", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FootballOrganization. As you add validations to FootballOrganization, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FootballOrganization.create! valid_attributes
      get football_organizations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      football_organization = FootballOrganization.create! valid_attributes
      get football_organization_url(football_organization)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_football_organization_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      football_organization = FootballOrganization.create! valid_attributes
      get edit_football_organization_url(football_organization)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FootballOrganization" do
        expect {
          post football_organizations_url, params: { football_organization: valid_attributes }
        }.to change(FootballOrganization, :count).by(1)
      end

      it "redirects to the created football_organization" do
        post football_organizations_url, params: { football_organization: valid_attributes }
        expect(response).to redirect_to(football_organization_url(FootballOrganization.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FootballOrganization" do
        expect {
          post football_organizations_url, params: { football_organization: invalid_attributes }
        }.to change(FootballOrganization, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post football_organizations_url, params: { football_organization: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested football_organization" do
        football_organization = FootballOrganization.create! valid_attributes
        patch football_organization_url(football_organization), params: { football_organization: new_attributes }
        football_organization.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the football_organization" do
        football_organization = FootballOrganization.create! valid_attributes
        patch football_organization_url(football_organization), params: { football_organization: new_attributes }
        football_organization.reload
        expect(response).to redirect_to(football_organization_url(football_organization))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        football_organization = FootballOrganization.create! valid_attributes
        patch football_organization_url(football_organization), params: { football_organization: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested football_organization" do
      football_organization = FootballOrganization.create! valid_attributes
      expect {
        delete football_organization_url(football_organization)
      }.to change(FootballOrganization, :count).by(-1)
    end

    it "redirects to the football_organizations list" do
      football_organization = FootballOrganization.create! valid_attributes
      delete football_organization_url(football_organization)
      expect(response).to redirect_to(football_organizations_url)
    end
  end
end
